sudo: required
services:
    - docker

before_install:
    - docker build -t alex067/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true alex067/docker-react npm run test -- --coverage
      